### ISSUE TITLE
Cannot download @datagov-cz versions

### ISSUE THREAD

**Issue by bindeali** [datagov-cz/assembly-line-shared#21]
Versions 0.3.3 and 0.3.4 are unavailable because 
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@datagov-cz%2fassembly-line-shared - Not found
npm ERR! 404
npm ERR! 404  '@datagov-cz/assembly-line-shared@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
``` 

Workaround is to use `npm i https://github.com/datagov-cz/assembly-line-shared.git` command instead.

**Comment by blcham** [comment]
I did the following:
- I created an organization @datagov-cz/al-developers 
- deployed version 0.3.4 in npmjs.org.  (I did not upload version 0.3.3. as it is same as 0.3.4.)
- set up new fine-grain secrets.NPM_TOKEN to deploy the next version (I hope it will work next time we publish)


I consider this issue resolved.

**Comment by bindeali** [comment]
Looks like it's working, closing.
